### ISSUE TITLE
categories disapearing from side bar block after I edit them

### ISSUE THREAD

**Issue by gingerling** [thirtybees/beesblogcategories#1]
I have recently been updating my category descriptions and other things. I noticed today that most of my categories are missing from the front end sidebar. 

I realised only the ones I updated were missing,
I tried shortening the names, this did not fix it
I tried toggling the sub category product display to on, this did not fix it
I reset the plugin, this did not fix it (but it did move the block to the bottom of the sidebar)

I tried editing another category by changing ONLY the description, this then removed the category from the sidebar
I changed the edit back as it was, but the category didn't return

I can't find any difference in the ones that are displaying and the ones that are not. They are working fine in the menu etc.

Now I just have two categorises on my live store!

**Comment by getdatakick** [comment]
You should check data stored in database, and look for differences between correctly and incorrectly displayed categories.

```
select * from tb_bees_blog_category;
select * from tb_bees_blog_category_lang;
```

**Comment by getdatakick** [comment]
I checked on my local environment, and editing categories have no negative impact.

I have discovered one minor issue, not related to this one -- disabled categories are always displayed. They should not

**Comment by gingerling** [comment]
ok, we didn't establish the cause but it was fixed by clicking the green ticks off and on again in the categories list. They were all green and the categories were working on the store, this only affected the product categories on the sidebar menu.

also I think I put this in the wrong place, I thought this was beesBLOCKcategories not beesblog. Don't know how to move it though.
